baseURL      = "/"
languageCode = "ru-ru"
title = "Nitra new site"
theme = "introduction"
enforce_ssl         = false
builddrafts         = false                             # Include pages with draft status of true
canonifyurls        = true                              # Turns relative urls into absolute urls
# disqusshortname   = "xxx"                             # Enable Disqus for comments
# googleAnalytics   = "UA-16087162-5"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true

[menu]
    [[menu.main]]
        name = "Главная"
        identifier = "home"
        url = "/"
        weight = 10
    [[menu.main]]
        name = "Как я работаю"
        identifier = "howWork"
        url = "/ru/how-it-work/"
        weight = 11
    [[menu.main]]
        name = "Подключение"
        identifier = "connection"
        url = "ru/connection/"
        weight = 12
    [[menu.main]]
        name = "Защита данных"
        identifier = "data-protect"
        url = "ru/data-protect/"
        weight = 13
    [[menu.main]]
        name = "Nitra vs Homo Sapiens"
        identifier = "connection"
        url = "ru/advantages/"
        weight = 14
    [[menu.main]]
        name = "Скорость загрузки сайта"
        identifier = "connection"
        url = "ru/speed/"
        weight = 14    
    [[menu.main]]
        name = "Алгоритмы сжатия изображений"
        identifier = "algorithm"
        url = "ru/speed-optimization-algorithms/"
        weight = 15
    [[menu.main]]
        name = "Облако или сервер?"
        identifier = "cloud-server"
        url = "ru/cloud-server/"
        weight = 16
    [[menu.main]]
        name = "Раздел аббревиатур2"
        identifier = "glossary"
        url = "ru/glossary/"
        weight = 17
    [[menu.main]]
        name = "Управление акаунтом"
        identifier = "account-management"
        url = "ru/account-management/"
        weight = 18
  

# enableMissingTranslationPlaceholders = true 
[params] 
    themestyle          = "light"                        # Choose 'light' or 'dark'
    introheight         = "fullheight"                       # Input either 'medium' or 'large' or z'fullheight'
    localtime           = false                          # Show your current local time in contact section
    timezone            = "America/Los_Angeles"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    dateform            = "Jan 2, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    cachebuster         = false                         # Add the current unix timestamp in query string for cache busting css assets (relevant in development mode)
    fadein              = false                          # Turn on/off the fade-in effect
    faviconfile         = "img/fav.ico"
    pygmentsStyle       = "monokai"                     # Choose theme: https://help.farbox.com/pygments.html
    pygmentsCodeFences  = true

    showblog            = false                          # Show Blog section on home page
    showprojects        = true                          # Show Projects section on home page
    projectcolumns      = "3"                           # Choose "2" or "3" columns for projects section
    placeholderimg      = "/img/workday.jpg"            # For Projects without image
    showallposts        = false                         # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
    showlatest          = false                          # Show latest blog post summary
    sharebuttons        = true                          # On post pages, show share this social buttons

    # Share buttons
    sharetwitter        = true
    sharefacebook       = true
    sharepinterest      = false
    sharegoogleplus     = true
    footerPhone         = "+371 267 59 278" 
    email               = "ai@nitra.ai"         # Shows in contact section, or leave blank to omit
    avatar              = "img/profile.jpg"             # Path to image in static folder eg. img/avatar.png, or comment out to remove
    # Navigation
    [params.breadcrumbs]


# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
    url = "https://twitter.com/nitra_ai"
    icon = "twitter"

[[params.social]]
    url = "https://www.facebook.com/Nitralabs-275977425891580"
    icon = "facebook"

#[[params.social]]
#    url = "https://linkedin.com/"
#    icon = "linkedin"


[languages]
[languages.ru]
    logo = "img/logo.svg"
    #welcome = "Привет, я"
    bloghead            = "Blog"
    firstname           = "Привет, я Nitra"
    namesite            = "Nitra"
    tagline             = "искусственный интеллект, виртуальный WEB инженер."
    optimization        = "Нахожу слабые зоны на сайте и исправляю их в режиме реального времени."
    mission             = "Оптимизирую скорость загрузки  сайта и настрою защиту данных."
    mission2            = "Если ты хочешь сделать апгрейд сайта -  мне нет равных!"
    effect              = "Я уже сделала 2,5 млн. замеров на сайте. и убедилась, что Ваш сайт теряет клиентов."
    effect2             = "Давай проверим  насколько твой сайт удобен клиентам:"
    scan                = "Давай посмотрим, в чем проблема."
    scan2               = "Я уже просканировал сайт Давай посмотрим результаты."

[[params.hero]]
    title = "hero title"

[languages.ua]
    firstname           = "Привіт, я Nitra"
    tagline             = "Я допоможу зробити \"Ваш сайт\" кращим"       # Appears after the introduction